# Profiles actives:
#     dev        (H2 Database - LOCAL)
#     qa         (Postgres Database)
#     prod       (Heroku Postgres Database with flyway)

spring:
  profiles:
    active: ${APP_PROFILE:dev}


  datasource:
    url: jdbc:h2:file:~/db/myfinacial
    username: sa
    password:


  jpa:
#    generate-ddl: false
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


  flyway:
    enabled: false


jwt:
  secret: TestYourMind
  expiration: 86400000


email:
  sender: my.financial.v2@gmail.com
  recipient: my.financial.v2@gmail.com
  app_link_access: http://localhost:8080/login