spring:

  datasource:
    url: jdbc:mysql://localhost:3306/myfinacial?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 12qwaszx

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


  mail:
    host: smtp.gmail.com
    port: 587
    username: my.financial.v2
    password: 123@mudarRR
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true