spring:

  datasource:
    url: jdbc:h2:file:~/db/myfinacial
    username: sa
    password:

  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop