spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12qwaszx


  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


  mail:
    host: smtp.gmail.com
    port: 587
    username: my.financial.v2
    password: 123@mudar
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  flyway:
    enabled: false
    locations: classpath:/db/migration


email:
  app_link_access: http://localhost:8080/login

