spring:

  datasource:
    url: ${DATABASE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    platform: ${SPRING_JPA_DATABASE-PLATFORM}


  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DLL_AUTO}


  mail:
    host: smtp.gmail.com
    port: 587
    username: my.financial.v2
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true


flyway:
  locations: classpath:/db/migration


email:
  app_link_access: ${APP_LINK_ACCESS}